{{- if .Values.objects.job }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "testbed.fullname" . }}
  labels:
    {{- include "testbed.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testbed.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        {{- if .Values.appFlags.debug }}
          - "--debug"
        {{- end }}
        {{- if .Values.appFlags.iterations }}
          - "--iterations={{ .Values.appFlags.iterations }}"
        {{- end }}
        {{- if .Values.appFlags.sleepSec }}
          - "--sleepSec={{ .Values.appFlags.sleepSec }}"
        {{- end }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}
{{- end }}
