name: Draft Image Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    if: ${{ (github.event_name == 'pull_request') || !contains(github.event.head_commit.message, 'Bump Helm chart versions') }}
    name: Autolabeler and release drafter
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Command `gh pr edit` needs to run in a repository,
      # so fetch a single file to make next step succeed
      - name: Checkout GitHub Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        if: github.event_name == 'pull_request'
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - name: Remove labels in preparation for autolabeler
        if: github.event_name == 'pull_request'
        run: |
          gh pr edit ${{ github.event.number }} \
            --remove-label "Release/break,Release/feat,Release/fix,Release/other"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Release drafter
        uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        id: draft-image-release
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          # To achive consistent results with different branches
          # Source: https://github.com/release-drafter/release-drafter/issues/1061#issuecomment-1032888355
          commitish: "${{ github.ref_name }}"
          config-name: draft-image-release-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
